spring:
  application:
    name: aurora-agent

  ai:
    openai:
      api-key: ${openai.api-key}
      base-url: ${openai.base-url}
      chat:
        options:
          model: gpt-4o
      embedding:
        api-key: ${openai.api-key}
        base-url: ${openai.base-url}
        options:
          model: "text-embedding-ada-002"