spring:
  application:
    name: aurora-agent

  ai:
    openai:
      api-key:
      base-url:
      chat:
        options:
          model: "gpt-4o-mini"
      embedding:
        enabled: true
        api-key:
        base-url:
        options:
          model: "text-embedding-ada-002"

logging:
  level:
    'org.springframework.ai': debug
