spring:
  application:
    name: aurora-agent

  ai:
    openai:
      api-key: sk-SgvKCkKZMKjQua9Y45D61aF17c824832A6Ff339544A7E1A4
      base-url:  https://aiapi.cubeai.com.cn
      chat:
        options:
          model: "gpt-4o"

    vectorstore:
      redis:
        initialize-schema: true
        index: aurora-knowledge

  data:
    redis:
      password: 111111

logging:
  level:
    'org.springframework.ai': debug

