spring:
  application:
    name: aurora-agent

  ai:
    openai:
      api-key: GHCPUURPSO31GIW8XOR7QBNRRC5CYS6ORJXREM1S
      base-url:  https://ai.gitee.com
      chat:
        options:
          model: Qwen2.5-Coder-32B-Instruct

    vectorstore:
      redis:
        initialize-schema: true
        index: aurora-knowledge

  data:
    redis:
      password: 111111

logging:
  level:
    'org.springframework.ai': debug

