spring:
  application:
    name: aurora-agent

  ai:
    openai:

      chat:
        options:
          model: gpt-4o-mini
      embedding:
        enabled: true

        options:
          model: "text-embedding-ada-002"

logging:
  level:
    'org.springframework.ai': debug
